Update ca-certificates for Fedora test Docker image (#35047)
### Details:
The old problem (https://github.com/openvinotoolkit/openvino/pull/34596)
appeared again today:

```
Intel(R) Distribution of OpenVINO 2023          0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'OpenVINO':
  - Curl error (60): SSL peer certificate or SSH remote key was not OK for https://yum.repos.intel.com/openvino/2023/repodata/repomd.xml [SSL certificate problem: unable to get local issuer certificate]
Error: Failed to download metadata for repo 'OpenVINO': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

`yum.repos.intel.com` TLS certificate was updated, but we use Fedora
version that is so old it doesn't receive updates for `ca-certificates`
package, so it stopped trusting the root certificate that signs
`yum.repos.intel.com` certificate.